import React,{useState,useEffect,useMemo,useRef} from 'react';
import {words,phrases} from './data/compiled';
import {grammar,lessons} from './data/course';
import {transcribe,alphabet} from './data/phonetics';
const KEY='slovak_lingua_progress_v1';
const fresh=()=>({version:1,everLearned:[],learned:[],reviews:{},completed:[],favorites:[],hidden:[],custom:[],results:[],goal:10,daily:{},theme:'system'});
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function load(){try{let s=JSON.parse(localStorage.getItem(KEY));return s?.version===1?{...fresh(),...s}:fresh();}catch{return fresh();}}
const normal=s=>s.toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const shuffled=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const nav=[['home','⌂','Обзор'],['course','▤','Курс с нуля'],['alphabet','Aa','Алфавит'],['words','▦','Словарь'],['train','◎','Тренировка'],['grammar','§','Грамматика'],['phrases','◇','Разговорник'],['reference','№','Числа и даты'],['settings','⚙','Настройки']];
function Cyrillic({text}){return <span className="trans">[{transcribe(text)}]</span>;}
function Example({sk,ru}){return <div className="example"><strong lang="sk">{sk}</strong><Cyrillic text={sk}/><span>{ru}</span></div>;}
function Section({s}){return <section className="panel"><h3>{s.title}</h3>{s.body&&<p>{s.body}</p>}{s.rows&&<div className="table-wrap"><table><thead><tr>{s.headers.map((v,i)=><th key={i}>{v}</th>)}</tr></thead><tbody>{s.rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}</section>;}
function Quiz({questions,onDone,spelling=false}){
 const [index,setIndex]=useState(0),[answer,setAnswer]=useState(null),[value,setValue]=useState(''),[score,setScore]=useState(0),[done,setDone]=useState(false);
 const q=questions[index];
 if(done)return <div className="panel result"><span className="eyebrow">Тренировка завершена</span><h2>{score} / {questions.length}</h2><p>{score/questions.length>=.8?'Отлично! Можно двигаться дальше.':'Повторите ошибки и попробуйте ещё раз.'}</p><button className="primary" onClick={()=>onDone(score,questions.length)}>Сохранить результат</button></div>;
 if(!q)return <div className="panel">Нет заданий. Выберите другую тему.</div>;
 const check=v=>{if(answer!==null)return;let ok=normal(v)===normal(q[1]);if(spelling)ok=v.trim().toLowerCase().normalize('NFC')===q[1].toLowerCase().normalize('NFC');setAnswer(ok);if(ok)setScore(n=>n+1);};
 return <div className="panel quiz"><div className="row spread"><span className="eyebrow">Задание {index+1} / {questions.length}</span><span>{score} верно</span></div><h2>{q[0]}</h2>{spelling?<form onSubmit={e=>{e.preventDefault();check(value)}}><label>Напишите по-словацки<input autoFocus value={value} onChange={e=>setValue(e.target.value)} disabled={answer!==null} placeholder="Ваш ответ" autoComplete="off" spellCheck="false"/></label><div className="letters">{'áäčďéíĺľňóôŕšťúýž'.split('').map(c=><button type="button" key={c} disabled={answer!==null} onClick={()=>setValue(v=>v+c)}>{c}</button>)}</div><button className="primary" disabled={answer!==null||!value.trim()}>Проверить</button><p className="muted">В письме долгота и диакритика обязательны.</p></form>:<div className="options">{q[2].map(v=><button key={v} disabled={answer!==null} onClick={()=>check(v)}>{v}</button>)}</div>}{answer!==null&&<div className={'feedback '+(answer?'good':'bad')} role="status"><strong>{answer?'Правильно':'Правильный ответ: '+q[1]}</strong>{/[a-z]/i.test(q[1])&&q[1].length>2&&<Cyrillic text={q[1]}/>}<button className="primary" onClick={()=>{if(index===questions.length-1)setDone(true);else{setIndex(i=>i+1);setAnswer(null);setValue('');}}}>{index===questions.length-1?'Итог':'Дальше →'}</button></div>}</div>;
}
function Flashcards({deck,onRate,onExit}){
 const [i,setI]=useState(0),[show,setShow]=useState(false);let w=deck[i];
 if(!w)return <div className="panel result"><h2>Карточки пройдены</h2><p>Результаты сохранены. Слова с ошибками попадут в ближайшее повторение.</p><button className="primary" onClick={onExit}>К тренировкам</button></div>;
 const rate=ok=>{onRate(w.id,ok);setI(n=>n+1);setShow(false);};
 return <><div className="row spread"><span className="eyebrow">Карточка {i+1} / {deck.length}</span><button onClick={onExit}>Завершить</button></div><div className="flash panel"><span className="tag">{w.level} · {w.category}</span><h2 lang="sk">{w.sk}</h2><span className="trans">[{w.transcription||transcribe(w.sk)}]</span>{show?<><h3>{w.ru}</h3><div className="row center"><button onClick={()=>rate(false)}>Повторить</button><button className="primary" onClick={()=>rate(true)}>Знаю ✓</button></div></>:<button className="primary" onClick={()=>setShow(true)}>Показать перевод</button>}</div><p className="muted center">Не знаете слово? Прочитайте его, откройте перевод и выберите «Повторить».</p></>;
}
export default function App(){
 const routed=useRef(null);
 const [p,setP]=useState(load),[page,setPage]=useState(location.hash.slice(1)||'home'),[more,setMore]=useState(false),[detail,setDetail]=useState(null),[lessonTest,setLessonTest]=useState(false),[q,setQ]=useState(''),[cat,setCat]=useState('Все темы'),[level,setLevel]=useState('Все уровни'),[filter,setFilter]=useState('Все слова'),[limit,setLimit]=useState(40),[session,setSession]=useState(null),[notice,setNotice]=useState(''),[editor,setEditor]=useState(null),[draft,setDraft]=useState({sk:'',ru:'',level:'A1',transcription:''}),[refNumber,setRefNumber]=useState(26),[date,setDate]=useState(today()),[time,setTime]=useState('14:30');
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(p));}catch{setNotice('Не удалось сохранить данные: хранилище браузера недоступно или заполнено. Экспортируйте прогресс.');}document.documentElement.dataset.theme=p.theme;},[p]);
 useEffect(()=>{let fn=()=>{let next=location.hash.slice(1)||'home';if(routed.current===next){routed.current=null;return;}setPage(next);setDetail(null);setSession(null);setMore(false);};window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn);},[]);
 const update=fn=>setP(s=>fn(s));
 const go=where=>{if(location.hash!=='#'+where){routed.current=where;location.hash=where;}setPage(where);setDetail(null);setLessonTest(false);setSession(null);setMore(false);setQ('');setCat('Все темы');setLevel('Все уровни');setLimit(40);window.scrollTo(0,0);};
 useEffect(()=>{if(editor===null)return;const handle=e=>{if(e.key==='Escape')setEditor(null);if(e.key==='Tab'){const nodes=[...document.querySelectorAll('.modal button,.modal input,.modal select')].filter(el=>!el.disabled);let first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handle);return()=>document.removeEventListener('keydown',handle);},[editor]);
 const all=useMemo(()=>[...words,...p.custom].filter(w=>!p.hidden.includes(w.id)),[p.custom,p.hidden]);
 const categories=[...new Set(all.map(w=>w.category))];
 const due=all.filter(w=>!p.reviews[w.id]||p.reviews[w.id].due<=today());
 const filtered=all.filter(w=>(cat==='Все темы'||w.category===cat)&&(level==='Все уровни'||w.level===level)&&(!q||normal(w.sk+' '+w.ru).includes(normal(q)))&&(filter!=='Изученные'||p.learned.includes(w.id))&&(filter!=='Избранное'||p.favorites.includes('w'+w.id))&&(filter!=='Повторить'||!p.reviews[w.id]||p.reviews[w.id].due<=today()));
 const rate=(id,ok)=>update(s=>{let old=s.reviews[id]||{box:0};let box=ok?Math.min(old.box+1,5):0;let d=new Date();d.setDate(d.getDate()+[0,1,3,7,14,30][box]);let learned=ok?[...new Set([...s.learned,id])]:s.learned.filter(x=>x!==id);let daily={...s.daily};if(ok&&!s.everLearned.includes(id))daily[today()]=(daily[today()]||0)+1;return {...s,learned,daily,everLearned:ok?[...new Set([...s.everLearned,id])]:s.everLearned,reviews:{...s.reviews,[id]:{box,due:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}}};});
 const favorite=id=>update(s=>({...s,favorites:s.favorites.includes(id)?s.favorites.filter(x=>x!==id):[...s.favorites,id]}));
 const saveResult=(score,total,topic)=>{update(s=>({...s,results:[...s.results,{date:today(),score,total,topic}].slice(-200)}));setSession(null);setNotice(`Результат сохранён: ${score} из ${total}.`);};
 const start=(mode)=>{const deck=shuffled(filtered).slice(0,Math.min(10,filtered.length));if(!deck.length){setNotice('По выбранным фильтрам нет слов. Измените фильтры.');return;}if(mode==='cards'){setSession({mode,deck});return;}const questions=deck.map(w=>[mode==='spelling'?w.ru:`Выберите перевод: ${w.sk}`,mode==='spelling'?w.sk:w.ru,shuffled([w.ru,...shuffled([...new Set(all.filter(a=>a.ru!==w.ru).map(a=>a.ru))]).slice(0,3)])]);setSession({mode,questions});};
 const exportProgress=()=>{let blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='slovak-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
 const importProgress=async e=>{try{let file=e.target.files[0];if(!file)return;if(file.size>2e6)throw Error('слишком большой файл');let data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.learned)||!Array.isArray(data.custom)||!Array.isArray(data.completed)||!Array.isArray(data.favorites)||!Array.isArray(data.hidden)||!Array.isArray(data.results)||!data.reviews||!data.daily||typeof data.goal!=='number'||data.goal<1||data.goal>100)throw Error('неверный формат');const ids=new Set();for(let w of data.custom){if(!Number.isInteger(w.id)||w.id<10001||ids.has(w.id)||typeof w.sk!=='string'||!w.sk.trim()||typeof w.ru!=='string'||!w.ru.trim()||typeof w.category!=='string'||(w.transcription!==undefined&&typeof w.transcription!=='string')||!['A1','A2','B1'].includes(w.level))throw Error('неверный формат слов');ids.add(w.id);}if(data.everLearned&&!Array.isArray(data.everLearned))throw Error('неверный формат истории');for(let k of ['learned','completed','hidden',...(data.everLearned?['everLearned']:[])])if(!data[k].every(x=>Number.isInteger(x)))throw Error('неверный формат прогресса');if(!data.favorites.every(x=>typeof x==='string'))throw Error('неверный формат избранного');for(let v of Object.values(data.reviews))if(typeof v.due!=='string'||!Number.isInteger(v.box)||v.box<0||v.box>5)throw Error('неверный формат повторений');if(!Object.values(data.daily).every(x=>Number.isFinite(x)&&x>=0))throw Error('неверный формат статистики');if(!['system','light','dark'].includes(data.theme))throw Error('неверная тема');if(!data.results.every(x=>typeof x.date==='string'&&typeof x.topic==='string'&&Number.isFinite(x.score)&&Number.isFinite(x.total)))throw Error('неверный формат результатов');if(confirm('Импорт заменит текущий прогресс и свои слова. Продолжить?')){setP({...fresh(),...data});setNotice('Прогресс импортирован.');}}catch(err){setNotice('Не удалось импортировать файл: '+err.message);}e.target.value='';};
 const saveWord=e=>{e.preventDefault();const sk=draft.sk.trim(),ru=draft.ru.trim();if(!sk||!ru)return;if(all.some(w=>normal(w.sk)===normal(sk)&&w.id!==editor)){setNotice('Такое слово уже есть в словаре.');return;}update(s=>{let id=editor==='new'?Math.max(10000,...s.custom.map(w=>w.id))+1:editor;let w={...draft,sk,ru,id,category:'Мои слова'};return {...s,custom:editor==='new'?[...s.custom,w]:s.custom.map(x=>x.id===id?w:x)};});setEditor(null);setNotice('Слово сохранено.');};
 const openTopic=(id,lesson=false)=>{setDetail({id,lesson});setLessonTest(false);window.scrollTo(0,0);};
 const topic=detail&&grammar.find(g=>g.id===detail.id),lesson=detail&&lessons.find(l=>l.topic===detail.id);
 let body;
 const filters=<div className="filters"><label className="search">Поиск<input placeholder="Словацкое слово или перевод" value={q} onChange={e=>{setQ(e.target.value);setLimit(40)}}/></label><label>Тема<select aria-label="Тема" value={cat} onChange={e=>{setCat(e.target.value);setLimit(40)}}>{['Все темы',...categories].map(c=><option key={c}>{c}</option>)}</select></label><label>Уровень<select aria-label="Уровень" value={level} onChange={e=>setLevel(e.target.value)}>{['Все уровни','A1','A2','B1'].map(c=><option key={c}>{c}</option>)}</select></label><label>Набор<select aria-label="Набор" value={filter} onChange={e=>setFilter(e.target.value)}>{['Все слова','Избранное','Изученные','Повторить'].map(c=><option key={c}>{c}</option>)}</select></label></div>;
 if(topic)body=<><button onClick={()=>{setDetail(null);setLessonTest(false)}}>← К списку</button><div className="titleblock"><span className="eyebrow">{detail.lesson?`Урок ${lesson.id} / ${lessons.length}`:'Грамматический справочник'} · {topic.level}</span><h1>{topic.title}</h1></div>{lessonTest?<Quiz key={topic.id} questions={topic.quiz} onDone={(score,total)=>{update(s=>({...s,completed:score/total>=.8?[...new Set([...s.completed,lesson.id])]:s.completed,results:[...s.results,{date:today(),score,total,topic:topic.title}].slice(-200)}));setLessonTest(false);setNotice(score/total>=.8?'Урок пройден! Переходите к следующему.':'Результат сохранён. Для завершения урока нужно не менее 80%.');}}/>:<><div className="stack">{topic.sections.map((s,i)=><Section key={i} s={s}/>)}</div><h2>Прочитайте и переведите</h2><div className="grid examples">{topic.examples.map(([sk,ru])=><Example key={sk} sk={sk} ru={ru}/>)}</div><div className="panel"><h3>Закрепите материал</h3><p>Прочитайте примеры, составьте 2–3 предложения о себе, затем пройдите тест. Порог завершения урока — 80% правильных ответов.</p><div className="row wrap"><button className="primary" onClick={()=>setLessonTest(true)}>Пройти тест · {topic.quiz.length} вопроса</button><button onClick={()=>{go('words');setCat(lesson.words)}}>Слова к уроку</button>{detail.lesson&&p.completed.includes(lesson.id)&&lesson.id<lessons.length&&<button onClick={()=>openTopic(lessons[lesson.id].topic,true)}>Следующий урок →</button>}</div></div></>}</>;
 else if(page==='home')body=<><div className="hero"><span className="eyebrow">SLOVENČINA · С НУЛЯ К УЧЁБЕ</span><h1>Ваш первый шаг<br/>в Словакию.</h1><p>Начните с букв. Научитесь общаться.<br/>Подготовьтесь к жизни в университете.</p><button className="primary" onClick={()=>{go('course');openTopic((lessons.find(l=>!p.completed.includes(l.id))||lessons[0]).topic,true)}}>{p.completed.length?'Продолжить курс':'Начать с нуля'} →</button><span className="hero-mark" aria-hidden="true">Aa<span>č ď ľ</span></span></div><div className="grid stats"><div className="panel"><span className="muted">Изучено слов</span><strong>{p.learned.filter(id=>all.some(w=>w.id===id)).length}<small> / {all.length}</small></strong></div><div className="panel"><span className="muted">Пройдено уроков</span><strong>{p.completed.length}<small> / {lessons.length}</small></strong></div><div className="panel"><span className="muted">Сегодня новых слов</span><strong>{p.daily[today()]||0}<small> / {p.goal}</small></strong></div></div><div className="grid two"><div className="panel"><span className="eyebrow">Ежедневная практика</span><h2>10 слов за один подход</h2><p>Карточки, тест на перевод и письмо. Интервалы повторения: 1, 3, 7, 14 и 30 дней.</p><button onClick={()=>go('train')}>Открыть тренировку →</button></div><div className="panel"><span className="eyebrow">Для будущего студента</span><h2>Первый день в вузе</h2><Example sk="Kde je študijné oddelenie?" ru="Где учебный отдел?"/><button onClick={()=>{go('phrases');setCat('Вуз и поступление')}}>Фразы для университета →</button></div></div><div className="note">Без озвучки. С русскими подсказками чтения. Прогресс хранится только на вашем устройстве — регулярно делайте резервную копию в настройках.</div></>;
 else if(page==='course')body=<><div className="titleblock"><span className="eyebrow">ПОШАГОВЫЙ ПЛАН · A0 → A2</span><h1>Курс с полного нуля</h1><p>Идите по порядку: правило → примеры → слова → тест. Все уроки доступны сразу.</p><div className="progress"><div style={{width:`${p.completed.length/lessons.length*100}%`}}/></div><p className="muted">Пройдено {p.completed.length} из {lessons.length} уроков</p></div><div className="lesson-list">{lessons.map(l=><button className="lesson" key={l.id} onClick={()=>openTopic(l.topic,true)}><span className={'lesson-num '+(p.completed.includes(l.id)?'complete':'')}>{p.completed.includes(l.id)?'✓':String(l.id).padStart(2,'0')}</span><span><strong>{l.title}</strong><span className="muted">{l.level} · около {l.minutes} минут · {grammar.find(g=>g.id===l.topic).quiz.length} вопроса</span></span><span aria-hidden="true">→</span></button>)}</div></>;
 else if(page==='alphabet')body=<><div className="titleblock"><span className="eyebrow">УРОК 01 · ЧИТАЕМ БЕЗ ОЗВУЧКИ</span><h1>Словацкий алфавит</h1><p>46 букв, включая сочетания dz, dž и ch. Слева — звук, ниже — название буквы.</p></div><div className="note">«:» означает долготу, не ударение. H — звонкий [ɦ], в подсказках условно «г». Ä в обычной речи часто звучит как «э». Словесная русская транскрипция приблизительная; у заимствований и связной речи бывают исключения.</div><div className="alphabet-grid">{alphabet.map(([letter,sound,name,ex])=><div className="panel letter-card" key={letter}><strong>{letter}<span>{letter.toLowerCase()}</span></strong><span className="letter-sound">{sound}</span><small>Название: {name}</small><div lang="sk">{ex}</div><Cyrillic text={ex}/></div>)}</div><button className="primary" onClick={()=>openTopic('sounds',true)}>Правила чтения и тест →</button></>;
 else if(page==='words')body=<><div className="titleblock"><span className="eyebrow">1000 ВСТРОЕННЫХ СЛОВ · A1–B1</span><h1>Мой словарь</h1><p>Поиск, свои слова и избранное. Уровни — ориентиры сложности, а не официальные списки CEFR.</p><button onClick={()=>{setEditor('new');setDraft({sk:'',ru:'',level:'A1',transcription:''})}}>+ Добавить слово</button></div>{filters}<div className="row spread"><span className="muted">Найдено: {filtered.length}</span><button onClick={()=>{go('train')}}>Тренироваться →</button></div><div className="word-list">{filtered.slice(0,limit).map(w=><div className="word-row" key={w.id}><button className={'star '+(p.favorites.includes('w'+w.id)?'selected':'')} aria-label={p.favorites.includes('w'+w.id)?'Убрать из избранного':'Добавить в избранное'} onClick={()=>favorite('w'+w.id)}>{p.favorites.includes('w'+w.id)?'★':'☆'}</button><div><strong lang="sk">{w.sk}</strong><span className="trans">[{w.transcription||transcribe(w.sk)}]</span><span>{w.ru}</span><small>{w.category} · {w.level}{w.gender?' · '+w.gender:''}{p.learned.includes(w.id)?' · изучено ✓':''}</small></div><div className="row">{w.id>10000&&<button aria-label={'Редактировать '+w.sk} onClick={()=>{setEditor(w.id);setDraft(w)}}>✎</button>}<button aria-label={'Скрыть '+w.sk} onClick={()=>{if(confirm('Скрыть «'+w.sk+'» из обучения? Можно восстановить в настройках.'))update(s=>({...s,hidden:[...s.hidden,w.id]}));}}>×</button></div></div>)}</div>{!filtered.length&&<div className="panel">Ничего не найдено. Измените поиск или фильтры.</div>}{filtered.length>limit&&<button onClick={()=>setLimit(n=>n+40)}>Показать ещё 40</button>}</>;
 else if(page==='train')body=session?(session.mode==='cards'?<Flashcards deck={session.deck} onRate={rate} onExit={()=>setSession(null)}/>:<Quiz questions={session.questions} spelling={session.mode==='spelling'} onDone={(s,t)=>saveResult(s,t,session.mode==='spelling'?'Письмо':'Перевод')}/>):<><div className="titleblock"><span className="eyebrow">ВСПОМНИТЬ · ПРОВЕРИТЬ · НАПИСАТЬ</span><h1>Тренировка</h1><p>Выберите тему и уровень. В одном подходе до 10 слов. Отметки карточек задают график повторений.</p></div>{filters}<div className="grid three">{[['cards','Карточки','Вспомните перевод, затем проверьте себя.'],['quiz','Тест на перевод','Выберите правильный русский перевод.'],['spelling','Письмо','Напишите слово по русскому переводу.']].map(([mode,title,desc])=><div className="panel" key={mode}><h2>{title}</h2><p>{desc}</p><button className="primary" onClick={()=>start(mode)}>Начать →</button></div>)}</div><div className="note">Доступно в наборе: {filtered.length}. Не начаты или ждут повторения: {due.length}. Чтобы учить только новые слова или повторять старые, выберите набор «Повторить». Тесты сохраняют баллы; статус «изучено» отмечается в карточках.</div></>;
 else if(page==='grammar')body=<><div className="titleblock"><span className="eyebrow">СПРАВОЧНИК · A1–A2</span><h1>Грамматика без пробелов</h1><p>От первых предложений до падежей, трёх времён и вида глагола. Откройте тему для таблиц, примеров и теста.</p></div><div className="grid two">{grammar.map(g=><button className="topic-card panel" key={g.id} onClick={()=>openTopic(g.id)}><span className="tag">{g.level}</span><h3>{g.title}</h3><span className="muted">{g.sections.length} раздела · практика →</span></button>)}</div><div className="note">Это подробный учебный конспект основных тем A1–A2, а не исчерпывающая академическая грамматика. Для редких исключений сверяйтесь со словарём и преподавателем.</div></>;
 else if(page==='phrases'){let list=phrases.filter(f=>(cat==='Все темы'||cat===f.category)&&(!q||normal(f.sk+' '+f.ru).includes(normal(q)))&&(filter!=='Избранное'||p.favorites.includes('p'+f.id)));body=<><div className="titleblock"><span className="eyebrow">129 ГОТОВЫХ ФРАЗ · 11 СИТУАЦИЙ</span><h1>Говорить по делу</h1><p>Магазин, транспорт, врач, общежитие и университет. Фразы с «хотел бы» приведены с указанием рода там, где есть варианты.</p></div><div className="filters"><label className="search">Поиск<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Фраза или перевод"/></label><label>Ситуация<select aria-label="Тема" value={cat} onChange={e=>setCat(e.target.value)}>{['Все темы',...new Set(phrases.map(f=>f.category))].map(c=><option key={c}>{c}</option>)}</select></label><label>Набор<select aria-label="Набор" value={filter==='Избранное'?'Избранное':'Все фразы'} onChange={e=>setFilter(e.target.value)}><option>Все фразы</option><option>Избранное</option></select></label></div>{cat==='Экстренная помощь'&&<div className="note emergency">В Словакии: 112 — единая экстренная служба, 155 — скорая, 158 — полиция. В экстренной ситуации не тратьте время на уроки: обратитесь за помощью.</div>}<div className="grid two">{list.map(f=><div className="panel phrase" key={f.id}><div className="row spread"><span className="tag">{f.category}</span><button className="star" aria-label="Избранная фраза" onClick={()=>favorite('p'+f.id)}>{p.favorites.includes('p'+f.id)?'★':'☆'}</button></div><Example sk={f.sk} ru={f.ru}/></div>)}</div>{!list.length&&<div className="panel">Нет фраз по выбранному запросу.</div>}</>;}
 else if(page==='reference'){const num=numberSk(Number(refNumber)),parts=date.split('-').map(Number),months=['januára','februára','marca','apríla','mája','júna','júla','augusta','septembra','októbra','novembra','decembra'],days=['prvého','druhého','tretieho','štvrtého','piateho','šiesteho','siedmeho','ôsmeho','deviateho','desiateho','jedenásteho','dvanásteho','trinásteho','štrnásteho','pätnásteho','šestnásteho','sedemnásteho','osemnásteho','devätnásteho','dvadsiateho','dvadsiateho prvého','dvadsiateho druhého','dvadsiateho tretieho','dvadsiateho štvrtého','dvadsiateho piateho','dvadsiateho šiesteho','dvadsiateho siedmeho','dvadsiateho ôsmeho','dvadsiateho deviateho','tridsiateho','tridsiateho prvého'];let dateSk=parts.length===3&&parts[2]&&parts[1]?`${days[parts[2]-1]} ${months[parts[1]-1]} ${numberSk(parts[0])}`:'';let [h,m]=time.split(':').map(Number);body=<><div className="titleblock"><span className="eyebrow">ПОВСЕДНЕВНЫЙ СПРАВОЧНИК</span><h1>Числа, время и даты</h1><p>Стройте числа и читайте даты. Для обычного общения пригодится цифровое чтение времени.</p></div><div className="grid two"><div className="panel"><h2>Число → слово</h2><label>Целое число от 0 до 9999<input type="number" min="0" max="9999" value={refNumber} onChange={e=>setRefNumber(e.target.value)}/></label>{num?<Example sk={num} ru={String(refNumber)}/>:<p role="status">Введите целое число от 0 до 9999.</p>}<small>Форма без существительного. Род и падеж могут менять форму числительного.</small></div><div className="panel"><h2>Дата</h2><label>Выберите дату<input type="date" min="1900-01-01" max="2099-12-31" value={date} onChange={e=>setDate(e.target.value)}/></label>{dateSk&&<Example sk={dateSk} ru="Чтение даты: день и месяц в родительном падеже."/>}</div></div><div className="panel"><h2>Время: цифровая форма</h2><label>Часы и минуты<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label>{time&&<Example sk={`${numberSk(h)} ${numberSk(m)}`} ru={`Показание ${time}. Это цифровое чтение, не разговорная форма «половина / четверть».`}/>}<p>Для назначения встречи: o 14:30 — o štrnástej tridsať. 1:30 — pol druhej; 1:15 — štvrť na dve; 1:45 — trištvrte na dve.</p></div><div className="row wrap"><button onClick={()=>openTopic('numbers')}>Грамматика числительных →</button><button onClick={()=>openTopic('time')}>Календарь и время →</button></div></>;}
 else if(page==='settings')body=<><div className="titleblock"><span className="eyebrow">УЧЁБА НА ВАШЕМ УСТРОЙСТВЕ</span><h1>Настройки и прогресс</h1></div><div className="grid two"><div className="panel"><h2>Ритм и оформление</h2><label>Цель: новых слов в день<select aria-label="Цель: новых слов в день" value={p.goal} onChange={e=>update(s=>({...s,goal:Number(e.target.value)}))}>{[5,10,15,20,30,50,...(![5,10,15,20,30,50].includes(p.goal)?[p.goal]:[])].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>Тема<select aria-label="Тема" value={p.theme} onChange={e=>update(s=>({...s,theme:e.target.value}))}><option value="system">Как на устройстве</option><option value="light">Светлая</option><option value="dark">Тёмная</option></select></label><p>Озвучки, микрофона и записи голоса нет.</p></div><div className="panel"><h2>Резервная копия</h2><p>Экспорт содержит прогресс, свои слова, избранное и результаты тестов. Удаление данных браузера удалит локальный прогресс.</p><div className="row wrap"><button className="primary" onClick={exportProgress}>Экспорт JSON</button><label className="file-label">Импорт JSON<input type="file" accept=".json,application/json" onChange={importProgress}/></label></div></div></div><div className="panel"><h2>Последние результаты</h2>{p.results.length?<div className="table-wrap"><table><thead><tr><th>Дата</th><th>Тема</th><th>Результат</th></tr></thead><tbody>{p.results.slice(-10).reverse().map((r,i)=><tr key={i}><td>{r.date}</td><td>{r.topic}</td><td>{r.score} / {r.total}</td></tr>)}</tbody></table></div>:<p>Здесь появятся результаты тестов и уроков.</p>}</div><div className="panel"><h2>Управление данными</h2><p>Скрыто слов: {p.hidden.length}. Скрытые слова не удаляются из резервной копии.</p><div className="row wrap"><button onClick={()=>update(s=>({...s,hidden:[]}))}>Восстановить скрытые слова</button><button className="danger" onClick={()=>{if(confirm('Сбросить ВЕСЬ прогресс, свои слова и настройки? Сначала сделайте экспорт.'))setP(fresh());}}>Сбросить всё</button></div></div><div className="panel"><h2>О приложении</h2><p>Slovak Lingua · версия 2.0. Основано на присланном Lingua Mini: React, карточки, тесты, письмо и локальный прогресс. Английские материалы заменены, добавлены словацкий курс и справочники.</p><p>Учебные пояснения составлены для русскоговорящего новичка. Кириллическая подсказка автоматически передаёт базовые правила, не все исключения и контекстные уподобления. Уровни слов условные. Приложение не выдаёт сертификат и не заменяет преподавателя.</p><p>Материалы для сверки: <a href="https://slovake.eu/grammar/pronunciation?hl=ru" target="_blank" rel="noreferrer">Slovake.eu — произношение</a>, <a href="https://slovake.eu/grammar/classes?hl=ru" target="_blank" rel="noreferrer">грамматика</a>.</p></div></>;
 else body=<div className="panel"><h2>Раздел не найден</h2><button onClick={()=>go('home')}>К обзору</button></div>;
 return <div className="app"><aside className="sidebar"><a href="#home" className="brand" onClick={e=>{e.preventDefault();go('home')}}><span className="brand-icon">S</span><span>Slovak<span className="brand-sub">LINGUA · ДЛЯ УЧЁБЫ</span></span></a><nav aria-label="Разделы">{nav.map(([id,icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><span aria-hidden="true" className="nav-icon">{icon}</span>{label}</button>)}</nav><div className="sidebar-foot">A0 → A2 · словарь до B1<br/>Офлайн · без озвучки</div></aside><div className="workspace"><header><span>Slovak Lingua <span className="muted">/ {nav.find(n=>n[0]===page)?.[2]||'Обзор'}</span></span><span className="badge">Сохранение на устройстве</span></header><main>{notice&&<div className="notice" role="status"><span>{notice}</span><button aria-label="Закрыть уведомление" onClick={()=>setNotice('')}>×</button></div>}{body}</main></div><nav className="mobile-nav" aria-label="Мобильная навигация">{[['home','⌂','Обзор'],['course','▤','Курс'],['train','◎','Практика'],['words','▦','Слова']].map(([id,icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><span aria-hidden="true">{icon}</span>{label}</button>)}<button className={more?'active':''} onClick={()=>setMore(!more)} aria-expanded={more}><span aria-hidden="true">•••</span>Ещё</button></nav>{more&&<div className="mobile-menu"><div className="row spread"><h3>Все разделы</h3><button onClick={()=>setMore(false)} aria-label="Закрыть меню">×</button></div>{nav.slice(2).filter(n=>!['words','train'].includes(n[0])).map(([id,icon,label])=><button key={id} onClick={()=>go(id)}>{icon} {label}</button>)}</div>}{editor!==null&&<div className="modal-backdrop"><div className="modal panel" role="dialog" aria-modal="true" aria-labelledby="editor-title"><div className="row spread"><h2 id="editor-title">{editor==='new'?'Новое слово':'Редактировать слово'}</h2><button onClick={()=>setEditor(null)} aria-label="Закрыть редактор">×</button></div><form onSubmit={saveWord}><label>Словацкое слово<input autoFocus required maxLength={100} value={draft.sk} onChange={e=>setDraft(s=>({...s,sk:e.target.value}))}/></label><label>Русский перевод<input required maxLength={200} value={draft.ru} onChange={e=>setDraft(s=>({...s,ru:e.target.value}))}/></label><label>Транскрипция (можно оставить пустой)<input maxLength={200} placeholder={transcribe(draft.sk)} value={draft.transcription||''} onChange={e=>setDraft(s=>({...s,transcription:e.target.value}))}/></label><label>Уровень<select value={draft.level} onChange={e=>setDraft(s=>({...s,level:e.target.value}))}>{['A1','A2','B1'].map(l=><option key={l}>{l}</option>)}</select></label><button className="primary">Сохранить</button></form></div></div>}</div>;
}
function numberSk(n){if(!Number.isInteger(n)||n<0||n>9999)return '';const small=['nula','jeden','dva','tri','štyri','päť','šesť','sedem','osem','deväť','desať','jedenásť','dvanásť','trinásť','štrnásť','pätnásť','šestnásť','sedemnásť','osemnásť','devätnásť'];if(n<20)return small[n];const tens=['','','dvadsať','tridsať','štyridsať','päťdesiat','šesťdesiat','sedemdesiat','osemdesiat','deväťdesiat'];if(n<100)return tens[Math.floor(n/10)]+(n%10?small[n%10]:'');if(n<1000)return (Math.floor(n/100)===1?'sto':Math.floor(n/100)===2?'dvesto':small[Math.floor(n/100)]+'sto')+(n%100?numberSk(n%100):'');return (Math.floor(n/1000)===1?'tisíc':Math.floor(n/1000)===2?'dvetisíc':small[Math.floor(n/1000)]+'tisíc')+(n%1000?numberSk(n%1000):'');}
